/**
 * @file ids.h
 * @author Aman Todi
 *
 *
 */

#ifndef TESTS_GAMELIB_IDS_H
#define TESTS_GAMELIB_IDS_H

enum IDs {
	IDM_LEVELZERO = wxID_HIGHEST + 1,
	IDM_LEVELONE,
	IDM_LEVELTWO,
	IDM_LEVELTHREE,
	IDM_SHRINK,
	IDM_ADDGARBAGEBUG,
	IDM_ADDNULLBUG,
	IDM_ADDREDUNDANCYBUG,
	IDM_ADDFEATUREBUG,
	IDM_ADDBUGSPIDER
};

#endif //TESTS_GAMELIB_IDS_H
